presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-bazel-build
    decorate: true
    always_run: true
    skip_branches:
    - release-\d+.\d+ # per-release job
    annotations:
      fork-per-release: "true"
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    extra_refs:
    - base_ref: master
      org: kubernetes
      repo: test-infra
    spec:
      containers:
      - image: launcher.gcr.io/google/bazel:0.25.2
        command:
        - bash
        args:
        - -c
        - |
          ../test-infra/hack/bazel.sh build --config=remote --remote_instance_name=projects/k8s-prow-builds/instances/default_instance $(bazel query --keep_going --noshow_progress "kind(.*_binary, rdeps(//... -//vendor/..., //...)) except attr('tags', 'manual', //...)") //build/release-tars
  - name: pull-kubernetes-bazel-test
    decorate: true
    always_run: true
    skip_branches:
    - release-\d+.\d+ # per-release job
    annotations:
      fork-per-release: "true"
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    extra_refs:
    - base_ref: master
      org: kubernetes
      repo: test-infra
    spec:
      containers:
      - image: launcher.gcr.io/google/bazel:0.25.2
        command:
        - ../test-infra/hack/bazel.sh
        args:
        - test
        - --config=unit
        - --config=remote
        - --remote_instance_name=projects/k8s-prow-builds/instances/default_instance
        - //...
        - --
        - -//build/...
        - -//vendor/...
postsubmits:
  kubernetes/kubernetes:
  - name: ci-kubernetes-bazel-build
    branches:
    - master
    annotations:
      fork-per-release: "true"
      fork-per-release-replacements: "latest-bazel.txt -> latest-bazel-{{.Version}}.txt"
      testgrid-dashboards: sig-release-master-blocking, google-unit
      testgrid-tab-name: bazel-build-master
      testgrid-alert-email: kubernetes-sig-testing-alerts@googlegroups.com, k8s-infra-oncall@google.com
      description: "Builds kubernetes using bazel"
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190813-5765933-master
        args:
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/logs"
        - "--timeout=60"
        - "--scenario=kubernetes_bazel"
        - "--" # end bootstrap args, scenario args below
        - "--build=//... -//vendor/..."
        - "--release=//build/release-tars"
        - "--gcs=gs://kubernetes-release-dev/ci"
        - "--version-suffix=-bazel"
        - "--publish-version=gs://kubernetes-release-dev/ci/latest-bazel.txt"
        resources:
          requests:
            memory: "6Gi"
  - name: post-kubernetes-bazel-build
    branches:
    - master
    decorate: true
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    extra_refs:
    - base_ref: master
      org: kubernetes
      repo: test-infra
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190813-5765933-master
        command:
        - bash
        args:
        - -c
        - |
          set -o errexit
          gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json
          ../test-infra/scenarios/kubernetes_bazel.py \
              --config=ci \
              "--build=//... -//vendor/..." \
              --release=//build/release-tars \
              --gcs=gs://kubernetes-release-dev/ci \
              --version-suffix=-bazel-rbe \
              --publish-version=gs://kubernetes-release-dev/ci/latest-bazel-rbe.txt

    annotations:
      testgrid-dashboards: sig-release-master-informing
      testgrid-tab-name: bazel-build-master
      description: 'OWNER: sig-testing; Builds kubernetes at each bommit using bazel with RBE'
  - name: ci-kubernetes-bazel-test # TODO(fejta): delete after 1m (dup of post-kubernetes-bazel-test)
    decorate: true
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    annotations:
      testgrid-dashboards: sig-release-master-blocking, google-unit
      testgrid-tab-name: bazel-test-master
      testgrid-alert-email: kubernetes-sig-testing-alert@googlegroups.com
      description: "OWNER: sig-testing. Tests kubernetes using bazel."
    extra_refs:
    - base_ref: master
      org: kubernetes
      repo: test-infra
    skip_branches:
    - release-\d+.\d+ # per-release job
    spec:
      containers:
      - image: launcher.gcr.io/google/bazel:0.25.2
        command:
        - ../test-infra/hack/bazel.sh
        args:
        - test
        - --config=unit
        - --config=remote
        - --remote_instance_name=projects/k8s-prow-builds/instances/default_instance
        - //...
        - //hack:verify-all
        - --
        - -//build/...
        - -//vendor/...

  - name: post-kubernetes-bazel-test
    decorate: true
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    annotations:
      fork-per-release: "true"
      testgrid-dashboards: sig-release-master-informing
      testgrid-tab-name: bazel-test-master
      description: 'OWNER: sig-testing; Runs kubernetes unit tests using bazel'
    extra_refs:
    - base_ref: master
      org: kubernetes
      repo: test-infra
    skip_branches:
    - release-\d+.\d+ # per-release job
    spec:
      containers:
      - image: launcher.gcr.io/google/bazel:0.25.2
        command:
        - ../test-infra/hack/bazel.sh
        args:
        - test
        - --config=unit
        - --config=remote
        - --remote_instance_name=projects/k8s-prow-builds/instances/default_instance
        - //...
        - //hack:verify-all
        - --
        - -//build/...
        - -//vendor/...

periodics:
# periodic bazel build jobs
- name: periodic-kubernetes-bazel-build-master
  interval: 5m
  decorate: true
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
  annotations:
    fork-per-release: "true"
    fork-per-release-replacements: "latest-bazel.txt -> latest-bazel-{{.Version}}.txt"
    fork-per-release-periodic-interval: 6h
    testgrid-dashboards: google-unit
    testgrid-tab-name: periodic-bazel-build-master
  extra_refs:
  - base_ref: master
    org: kubernetes
    repo: kubernetes
  - base_ref: master
    org: kubernetes
    repo: test-infra
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190813-5765933-master
      command:
      - bash
      args:
      - -c
      - |
        set -o errexit
        gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json
        ../test-infra/scenarios/kubernetes_bazel.py \
            --config=ci \
            "--build=//... -//vendor/..." \
            --release=//build/release-tars \
            --gcs=gs://kubernetes-release-dev/ci \
            --version-suffix=-bazel \
            --publish-version=gs://kubernetes-release-dev/ci/latest-bazel.txt

- name: periodic-kubernetes-bazel-build-canary
  interval: 1h
  decorate: true
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
  # do not fork
  extra_refs:
  - base_ref: master
    org: kubernetes
    repo: kubernetes
  - base_ref: master
    org: kubernetes
    repo: test-infra
  spec:
    containers:
    - image: launcher.gcr.io/google/bazel
      imagePullPolicy: Always
      command:
      - bash
      args:
      - -c
      - |
        set -o errexit
        gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json
        ../test-infra/scenarios/kubernetes_bazel.py \
            --config=ci \
            "--build=//... -//vendor/..." \
            --release=//build/release-tars \
            --gcs=gs://kubernetes-release-dev/ci \
            --version-suffix=-bazel \
            --publish-version=gs://kubernetes-release-dev/ci/latest-bazel.txt

# periodic bazel test jobs
  annotations:
    testgrid-dashboards: sig-testing-canaries
    testgrid-tab-name: bazel-build
    description: run kubernetes-bazel-build with latest image
- interval: 5m
  name: periodic-kubernetes-bazel-test-master
  decorate: true
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
  annotations:
    fork-per-release: "true"
    fork-per-release-periodic-interval: 6h
    testgrid-dashboards: google-unit
    testgrid-tab-name: periodic-bazel-test-master
  extra_refs:
  - base_ref: master
    org: kubernetes
    repo: kubernetes
  - base_ref: master
    org: kubernetes
    repo: test-infra
  spec:
    containers:
    - image: launcher.gcr.io/google/bazel:0.25.2
      command:
      - ../test-infra/hack/bazel.sh
      args:
      - test
      - --config=unit
      - --config=remote
      - --remote_instance_name=projects/k8s-prow-builds/instances/default_instance
      - //...
      - //hack:verify-all
      - --
      - -//build/...
      - -//vendor/...
- interval: 1h
  name: periodic-kubernetes-bazel-test-canary
  decorate: true
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
  extra_refs:
  - base_ref: master
    org: kubernetes
    repo: kubernetes
  - base_ref: master
    org: kubernetes
    repo: test-infra
  spec:
    containers:
    - image: launcher.gcr.io/google/bazel
      command:
      - ../test-infra/hack/bazel.sh
      args:
      - test
      - --config=unit
      - --config=remote
      - --remote_instance_name=projects/k8s-prow-builds/instances/default_instance
      - //...
      - //hack:verify-all
      - --
      - -//build/...
      - -//vendor/...
  annotations:
    testgrid-dashboards: sig-testing-canaries
    testgrid-tab-name: bazel-test
    description: run kubernetes-bazel-test with latest image
